// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "./ERC721Preset.sol";

contract ExtendedAsciiPlot is ERC721Preset {
    constructor() ERC721Preset("Extended ASCII Plot", "EAP", "") {}

    /**
     * @dev Creates a new token for `to`. The token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     */
    function mint(address to, uint256 tokenId) public {
        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        _safeMint(to, tokenId);
    }
}
